# Generated by Django 5.0.6 on 2024-07-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="stuemail2",
            field=models.EmailField(default="not neccesssary", max_length=70),
        ),
    ]
