# Generated by Django 5.0.6 on 2024-07-18 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0002_student_stuemail2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="stuemail2",
        ),
    ]
